[package]
name = "ipc_web_monitor"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
tokio = { version = "1.41", features = ["full"] }
warp = "0.3"
futures = "0.3"
chrono = "0.4"